pretrained: false
checkpoint: None
mode: train

model:
  model_name: RESNET
  channels: 64
  pooling_layers: 2
  padding_size: 11
  normalize: true
  dimensionality: 2
  train_loss_fn: l1
  val_loss_fn: l1
  regularization_factor: 100
  consecutive_slices: 1
  self_supervising_masks: true
  coil_combination_method: SENSE
  use_sens_net: false
  sens_chans: 8
  sens_pools: 4
  sens_mask_type: 2D
  fft_centered: true
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  complex_data: true
  log_images: true

  train_ds:
    data_path: /data/projects/recon/data/public/fastmri/knees/PD/multicoil_train/
    sense_path: /data/projects/recon/data/public/fastmri/knees/sensitivity_maps/PD/
    mask_path: /scratch/iskylitsis/data/PD/train_ssdu_masks_4x_eq/
    initial_predictions_path: None
    challenge: multicoil
    batch_size: 1
    sample_rate: 0.02
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    self_supervising_masks: true
    data_saved_per_slice: false
    complex_data: true
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: None
      accelerations:
        - 10
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: true
      use_seed: true
    half_scan_percentage: 0.0
    remask: false
    crop_size: [320, 368]
    kspace_crop: true
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: false
    max_norm: true
    fft_centered: true
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: true
    shuffle: true
    num_workers: 8
    drop_last: false
    pin_memory: false

  validation_ds:
    data_path: /data/projects/recon/data/public/fastmri/knees/PD/multicoil_val/
    sense_path: /data/projects/recon/data/public/fastmri/knees/sensitivity_maps/PD/
    mask_path: /scratch/iskylitsis/data/PD/val_ssdu_masks_4x_eq/
    initial_predictions_path: None
    challenge: multicoil
    batch_size: 1
    sample_rate: 0.02
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    self_supervising_masks: true
    data_saved_per_slice: false
    complex_data: true
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: None
      accelerations:
        - 10
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: true
      use_seed: true
    half_scan_percentage: 0.0
    remask: false
    crop_size: [320, 368]
    kspace_crop: true
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: false
    max_norm: true
    fft_centered: true
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: true
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

  optim:
    name: adam
    lr: 0.0005
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 100
  precision: 32
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 1
  check_val_every_n_epoch: 100
  max_steps: -1

exp_manager:
  exp_dir: ???
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: ???
  files_to_copy: [ ]
